version: "3"

includes:
  kind:
    taskfile: ./01-kind/Taskfile.yaml
    dir: ./01-kind
  app:
    taskfile: ./02-app/Taskfile.yaml
    dir: ./02-app
    vars:
      IMAGE_TAG: prod
      DB_USER: merchant
      DB_PASSWORD: foobarbaz
      DB_NAME: db
  manifests:
    taskfile: ./03-manifests/Taskfile.yaml
    dir: ./03-manifests
