apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: davidalej/traveling-merchant-backend:{{ backend.version }}
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: redis-cache-master.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          envFrom:
            - secretRef:
                name: database-url
            - secretRef:
                name: backend-cookies
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
