apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: app
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: "2"
    kluctl.io/create-only: "true"
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: davidalej/traveling-merchant-backend:{{ backend.version }}
          command: ["npm", "run", "prod-migration"]
          envFrom:
            - secretRef:
                name: db-migrator-password
      restartPolicy: OnFailure
