version: "3"

vars:
  DB_USER: merchant
  DB_PASSWORD: foobarbaz
  DB_NAME: db
  BACKEND_NETWORK: backend-network
  FRONTEND_IMAGE_REPO: davidalej/traveling-merchant-frontend
  BACKEND_IMAGE_REPO: davidalej/traveling-merchant-backend
  IMAGE_TAG: prod

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend

  backend:
    taskfile: ./backend/Taskfile.yaml
    dir: ./backend

  db:
    taskfile: ./db/Taskfile.yaml
    dir: ./db

  redis:
    taskfile: ./redis/Taskfile.yaml
    dir: ./redis

tasks:
  bootstrap-buildx-builder:
    desc: Bootstrap the builder
    cmds:
      - docker buildx create --name mybuilder --driver docker-container --driver-opt network=host --use
      - docker buildx inspect mybuilder --bootstrap
      - docker buildx use mybuilder

  run-local-registry:
    desc: Run a local registry
    cmds:
      - docker run -d -p 5000:5000 registry:2.8

  generate-docker-compose:
    desc: Generate docker compose with task variables.
    cmds:
      - |
        FRONTEND_IMAGE={{.FRONTEND_IMAGE_REPO}}:{{.IMAGE_TAG}} \
          BACKEND_IMAGE={{.BACKEND_IMAGE_REPO}}:{{.IMAGE_TAG}} \
          POSTGRES_USER={{.DB_USER}} \
          POSTGRES_PASSWORD={{.DB_PASSWORD}} \
          POSTGRES_DB={{.DB_NAME}} \
          DB_URL=postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@db:5432/{{.DB_NAME}} \
          envsubst < docker-compose.yaml.TEMPLATE \
          > docker-compose.yaml

  up:
    desc: Start docker compose full-stack application.
    cmds:
      - docker compose up --build

  down:
    desc: Remove docker compose full-stack application.
    cmds:
      - docker compose down
