version: "3"

vars:
  BACKEND_NETWORK: backend-network

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yaml
    dir: ./frontend
    vars:
      IMAGE_REPO: davidalej/traveling-merchant-frontend

  backend:
    taskfile: ./backend/Taskfile.yaml
    dir: ./backend
    vars:
      IMAGE_REPO: davidalej/traveling-merchant-backend

  db:
    taskfile: ./db/Taskfile.yaml
    dir: ./db

  redis:
    taskfile: ./redis/Taskfile.yaml
    dir: ./redis
    vars:
      IMAGE_REPO: davidalej/traveling-merchant-db-migrator

tasks:
  bootstrap-buildx-builder:
    desc: Bootstrap the builder
    cmds:
      - docker buildx create --name mybuilder --driver docker-container --driver-opt network=host --use
      - docker buildx inspect mybuilder --bootstrap
      - docker buildx use mybuilder

  run-local-registry:
    desc: Run a local registry
    cmds:
      - docker run -d -p 5000:5000 registry:2.8

  up:
    desc: Start docker compose full-stack application.
    cmds:
      - docker compose up --build

  down:
    desc: Remove docker compose full-stack application.
    cmds:
      - docker compose down
