version: "3"

env:
  CLUSTER_NAME: traveling-merchant

tasks:
  1-generate-config:
    desc: "Generate kind config with local absolute paths for PV mounts"
    cmds:
      - REPLACE_WITH_ABSOLUTE_PATH=${PWD} envsubst < kind-config.yaml.TEMPLATE > kind-config.yaml

  staging:1-create-cluster:
    desc: Create a Kubernetes cluster for staging using kind
    cmds:
      - kind create cluster --name staging --config kind-config.yaml

  staging:2-delete-cluster:
    desc: Delete staging kind Kubernetes cluster
    cmds:
      - kind delete cluster --name staging

  prod:1-create-cluster:
    desc: Create a Kubernetes cluster for production using kind
    cmds:
      - kind create cluster --name prod --config kind-config.yaml

  prod:2-delete-cluster:
    desc: Delete production kind Kubernetes cluster
    cmds:
      - kind delete cluster --name prod
