apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-with-backup-config
spec:
  instances: 2
  storage:
    size: 100Mi
  backup:
    retentionPolicy: "1d"
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/dev-db
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 2
      data:
        compression: gzip
  monitoring:
    enablePodMonitor: false
