version: "3"

vars:
  IMAGE_REPO: davidalej/traveling-merchant-frontend
  IMAGE_TAG: prod

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
          --push \
          .

  run:
    desc: Docker run nginx frontend.
    cmds:
      - |
        docker run -d \
          --name nginx-frontend \
          -p 8081:8080 \
          {{.IMAGE_REPO}}:{{.IMAGE_TAG}}

  delete:
    desc: Docker stop and remove frontend container.
    cmds:
      - |
        docker stop nginx-frontend
        docker rm nginx-frontend

  local-install:
    desc: install dependencies
    cmds:
      - npm install

  local-run:
    desc: Start react client
    cmds:
      - npm run dev
